spring:
  application:
    name: auth
  datasource:
    url: jdbc:h2:mem:authdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    dbcp2.driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      format_sql: true
      show_sql: true
      hibernate.format_sql: true
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080

auth:
  jwt:
    issuer: auth-service
    access-ttl-seconds: 1800
    refresh-ttl-seconds: 1209600
    secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,flyway