-- src/main/resources/db/migration/V1__init.sql
create table apps (
    id bigint generated by default as identity primary key,
    special_key varchar(100) not null unique,
    name varchar(255) not null,
    active boolean not null default true
);

create table users (
    id bigint generated by default as identity primary key,
    username varchar(100) not null unique,
    password_hash varchar(255) not null,
    enabled boolean not null default true
);

create table permissions (
    id bigint generated by default as identity primary key,
    code varchar(100) not null
);

create table roles (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    app_id bigint not null references apps(id)
);

create table role_permissions (
    role_id bigint not null references roles(id),
    permission_id bigint not null references permissions(id),
    primary key (role_id, permission_id)
);

create table user_app_roles (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    app_id bigint not null references apps(id),
    role_id bigint not null references roles(id),
    constraint uq_user_app_role unique(user_id, app_id, role_id)
);
